/**
 * router.tsx — TanStack Router factory.
 *
 * Creates and exports a typed router instance.
 * The routeTree is auto-generated by TanStack Router's
 * file-based routing plugin from files in routes/.
 */

import { createRouter as createTanStackRouter } from "@tanstack/react-router"
import { routeTree } from "./routeTree.gen"

export function createRouter() {
  const router = createTanStackRouter({
    routeTree,
    defaultPreload: "intent",
    scrollRestoration: true,
  })

  return router
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof createRouter>
  }
}
