/**
 * router.tsx — TanStack Router factory.
 *
 * Creates and exports a typed router instance.
 * Must export `getRouter` — the name is required by TanStack Start v1.159.x internals.
 * The virtual module `#tanstack-router-entry` aliases to this file,
 * and the runtime calls `import { getRouter } from "#tanstack-router-entry"`.
 *
 * The routeTree is auto-generated by TanStack Router's
 * file-based routing plugin from files in routes/.
 */

import { createRouter as createTanStackRouter } from "@tanstack/react-router"
import { routeTree } from "./routeTree.gen"

/**
 * Default loading indicator shown during route transitions.
 * In SPA mode, TanStack Start renders this instead of matched routes
 * for the prerendered shell HTML. Without this, the shell body is empty.
 *
 * Uses inline styles to avoid dependency on CSS loading.
 * @see https://tanstack.com/start/latest/docs/framework/react/guide/spa-mode
 */
function DefaultPendingComponent() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
        width: "100%",
        color: "oklch(0.985 0.002 247)",
        backgroundColor: "oklch(0.145 0.013 260)",
        fontFamily: "system-ui, -apple-system, sans-serif",
      }}
    >
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: "12px",
        }}
      >
        <div
          style={{
            width: "32px",
            height: "32px",
            border: "3px solid oklch(0.3 0.01 260)",
            borderTopColor: "oklch(0.7 0.15 250)",
            borderRadius: "50%",
            animation: "idumb-spin 0.8s linear infinite",
          }}
        />
        <span style={{ fontSize: "14px", opacity: 0.7 }}>Loading…</span>
        <style>{`@keyframes idumb-spin { to { transform: rotate(360deg) } }`}</style>
      </div>
    </div>
  )
}

function DefaultNotFoundComponent() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
        width: "100%",
        color: "oklch(0.985 0.002 247)",
        backgroundColor: "oklch(0.145 0.013 260)",
        fontFamily: "system-ui, -apple-system, sans-serif",
      }}
    >
      <div style={{ textAlign: "center" }}>
        <h1 style={{ fontSize: "48px", margin: "0 0 8px", fontWeight: 700 }}>404</h1>
        <p style={{ fontSize: "14px", opacity: 0.7, margin: 0 }}>Page not found</p>
      </div>
    </div>
  )
}

export function getRouter() {
  const router = createTanStackRouter({
    routeTree,
    defaultPreload: "intent",
    scrollRestoration: true,
    defaultPendingComponent: DefaultPendingComponent,
    defaultNotFoundComponent: DefaultNotFoundComponent,
    defaultPendingMs: 0,
  })

  return router
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
